# Generated by Django 4.0 on 2022-08-30 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='neatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastRefresh', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='cityData',
            fields=[
                ('neatdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='neatApi.neatdata')),
                ('cityName', models.CharField(max_length=50)),
                ('tz', models.CharField(max_length=50)),
                ('temp_c', models.FloatField()),
                ('temp_f', models.FloatField()),
                ('humidity', models.FloatField()),
                ('conditionIcon', models.URLField()),
            ],
            bases=('neatApi.neatdata',),
        ),
        migrations.CreateModel(
            name='finData',
            fields=[
                ('neatdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='neatApi.neatdata')),
                ('symbol', models.CharField(max_length=50)),
                ('dateRecent', models.DateTimeField()),
                ('closeRecent', models.FloatField()),
                ('openRecent', models.FloatField()),
                ('dateHistoric', models.DateTimeField()),
                ('closeHistoric', models.FloatField()),
            ],
            bases=('neatApi.neatdata',),
        ),
    ]
