# Generated by Django 4.0 on 2022-08-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neatApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citydata',
            name='conditionIcon',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='citydata',
            name='humidity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='citydata',
            name='temp_c',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='citydata',
            name='temp_f',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='citydata',
            name='tz',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
