# Generated by Django 4.0 on 2022-08-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neatApi', '0002_alter_citydata_conditionicon_alter_citydata_humidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neatdata',
            name='lastRefresh',
            field=models.DateTimeField(null=True),
        ),
    ]
