# Generated by Django 4.0 on 2022-08-30 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('neatApi', '0003_alter_neatdata_lastrefresh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neatdata',
            name='lastRefresh',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
