# Generated by Django 4.0 on 2022-09-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neatApi', '0005_alter_findata_closehistoric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='findata',
            name='currency',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='findata',
            name='previousClose',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='findata',
            name='previousCloseRefreshDate',
            field=models.DateTimeField(null=True),
        ),
    ]
